### ISSUE TITLE
How to import the trained model like you have

### ISSUE THREAD

**Issue by hoslack** [xxczaki/ship-classifier#1]
Hello @xxczaki , thanks a lot for your great explanation and good work. 

However, I tried using the Teachable machine but I can't understand how you exported your models to your project. Mine comes as code.

**Comment by xxczaki** [comment]
Hi, here are the steps:

1. Go to https://teachablemachine.withgoogle.com/train/image
2. Add classes, sample images, etc.
3. Train your model
4. Click the "Export Model" button
5. Select the "Download" option
![](https://imgur.com/JShKNzB.png)
6. Click the "Download my model" button
![](https://imgur.com/HOmWgLX.png)

That should work for you :smile:

**Comment by hoslack** [comment]
Thanks a lot @xxczaki ,
It worked for me.
